export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const SET_PRODUCTS = 'SET_PRODUCTS';
export const SET_FILTERED_PRODUCTS = 'SET_FILTERED_PRODUCTS';
export const CLEAR_PRODUCTS = 'CLEAR_PRODUCTS';
export const SET_PRODUCTS_ERORR = 'SET_PRODUCTS_ERORR';
